config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  root to: 'tweets#index'
  namespace :tweets do
    resources :searches, only: :index
  end
  resources :searches, only: :index
  resources :users do
    member do
      get 'like'
      get 'home'
    end
  end

  resources :quests, only: [:new, :create, :show, :destroy] do
    resources :brands
  end
  namespace :admin do
    resources :users
  end
  resources :tweets do
    collection do
      get 'commercial'
    end
    resources :likes, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user

  def index
    @users = User.all.order("created_at DESC")
    @quest = Quest.all
    @brand = Brand.all
  end

  private
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_brand, only: [:home, :show, :like]

  def home
    @user = User.find(params[:id])
    @quest = Quest.find_by(user_id: @user.id)
    @tweets = @user.tweets.last(4)
    @likes = Like.where(user_id: @user.id).last(4)
    @brands = Brand.find_by(user_id: @user.id)
  end


  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @tweets = @user.tweets
  end

  def like
    @user = User.find(params[:id])
    @likes = Like.where(user_id: @user.id)
  end
end

private

private
  def set_brand
    @parents = Category.all
    @brand = Brand.all
  end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/users/home.html.haml
.wrapper
  = render "shared/side_bar"
  .iitem
    = @user.nickname
    のマイページ
    .test
      .mypage__name
        ユーザー名 : 
        .mypage__name__myname
          = @user.nickname
      .mypage__item
        最近の投稿
        .item
          - @tweets.each do |tweet|
            .item__box.mypage__size
              = link_to "/tweets/#{tweet.id}", method: :get, class: "item__link" do
                = image_tag tweet.toukouimages.first.image.url, class: "item__box__view"
      .mypage__item
        お気に入りアイテム
        .item
          - @likes.each do |like|
            - tweet = Tweet.find_by(id: like.tweet_id)
            .item__box.mypage__size
              = link_to "/tweets/#{tweet.id}", method: :get, class: "item__link" do
                = image_tag tweet.toukouimages.first.image.url, class: "item__box__view"
      .mypage__name
        マイブランド:
        - if @brands.present?
          .mypage__name__myname
            = @brands.name
        - elsif @quest.present?
          .mypage__name__myname
            = @quest.brandname
          .iitem__date__bottan__shop
            申請中
        - elsif user_signed_in? && current_user.id == @user.id
          .mypage__name__myname
            .iitem__date__bottan__shop
              = link_to new_quest_path do
                申請する
        - else
          .mypage__name__myname
            登録なし

app/views/users/like.html.haml
.wrapper
= render "shared/side_bar"
.main-image
  お気に入りアイテム
  - if @likes.present?
    = render "shared/likelist", { new: @likes }
  - else 
    .non_item
      まだお気に入りがありません

app/views/users/show.html.haml
.wrapper
= render "shared/side_bar"
.main-image
  投稿したアイテム
  - if @tweets.present?
    = render "shared/new-list", { new: @tweets }
  - else 
    .non_item
      まだ投稿がありません