config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  root to: 'tweets#index'
  namespace :tweets do
    resources :searches, only: :index
  end
  resources :searches, only: :index
  resources :users do
    member do
      get 'like'
      get 'home'
    end
  end

  resources :quests, only: [:new, :create, :show, :destroy] do
    resources :brands
  end
  namespace :admin do
    resources :users
  end
  resources :tweets do
    collection do
      get 'commercial'
    end
    resources :likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  belongs_to :quest
  has_many :tweets

  def self.brandsearch(search)
    @brand = Brand.find_by(['name LIKE ?', "%#{search}%"])
    if @brand.present?
      Tweet.where(['brand_id LIKE ?', "%#{@brand.id}%"])
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tweets

  def self.categorysearch(search)
    @category = Category.find_by(['name LIKE ?', "%#{search}%"])
    if @category.present?
      Tweet.where(['category_id LIKE ?', "%#{@category.id}%"])
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/quest.rb
class Quest < ApplicationRecord
  validates :brandname, presence: true
  has_one :brand
end

app/models/tag.rb
class Tag < ApplicationRecord
  
  before_save :downcase_tag_name
  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tweets, through: :tweet_tag_relations
  validates :tag_name, uniqueness: true, length: { maximum: 50 }
  private

  def downcase_tag_name
    self.tag_name.downcase!
  end

  def self.tagsearch(search)
    @tag = Tag.find_by(['tag_name LIKE ?', "%#{search}%"])
    if @tag.present?
      Tweet.left_joins( :tweet_tag_relations ).where(['tag_id LIKE ?', "%#{@tag.id}%"])
    end
  end
end

app/models/toukouimage.rb
class Toukouimage < ApplicationRecord
  validates :image, presence: true
  mount_uploader :image, ImageUploader
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  validates :catchcopy, :text, :category_id, :brand_id, presence: true
  belongs_to :user
  belongs_to :category
  belongs_to :brand
  has_many :toukouimages, dependent: :destroy
  accepts_nested_attributes_for :toukouimages, allow_destroy: true
  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tags, through: :tweet_tag_relations
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  validates_associated :toukouimages
  validates :toukouimages, presence: true

  def self.search(search)
    return Tweet.all unless search
    Tweet.where(['catchcopy LIKE ? OR text LIKE ?', "%#{search}%", "%#{search}%"])
  end

  

  def save_tags(tag_list)
    tag_list.each do |tag|
      unless find_tag = Tag.find_by(tag_name: tag.downcase)
        begin
          self.tags.create!(tag_name: tag)
        rescue
          nil
        end
      else
        TweetTagRelation.create!(tweet_id: self.id, tag_id: find_tag.id)
      end
    end
  end
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
 


  def create
    @brands = Brand.create(brand_params)
    @quest = Quest.find_by(user_id: brand_params[:user_id])
    if @brands.save
      @quest.delete
      redirect_to admin_users_path, notice: '登録を完了しました'
    else
      redirect_to admin_users_path, notice: '登録できませんでした'
    end
  end

  

  private
  def brand_params
    params.require(:brand).permit(:name, :user_id)
  end

  def set_brand
    @parents = Category.all
    @brand = Brand.all
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(tweet_id: params[:tweet_id])
    redirect_back(fallback_location: root_path)
  end

 

  def destroy
    @like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :set_brand, only: [:new]
  before_action :admin_user, only: [:show]


  def new
    @quest = Quest.new
  end

  def create
    @quest = Quest.new(brand_params)
    if @quest.save
      redirect_to root_path, notice: '申請を完了しました'
    else
      redirect_to root_path, notice: '申請できませんでした'
    end
  end

  def show
    @quest = Quest.find(params[:id])
    @brands = Brand.new
  end

  def destroy
    @quest = Quest.find(params[:id])
    @quest.delete
    redirect_to admin_users_path, notice:'申請を否認しました'
  end

  

  private
  def brand_params
    params.require(:quest).permit(:brandname).merge(user_id: current_user.id)
  end
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

  def set_brand
    @parents = Category.all
    @brand = Brand.all
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :move_to_index, except: [:index, :search]
  before_action :set_brand, except: [:destroy]
  before_action :set_item, only: [:show, :edit, :update]
  def index
    @good_ranks = Tweet.includes(:user).find(Like.group(:tweet_id).order('count(tweet_id) desc').limit(4).pluck(:tweet_id))
    @tweets = Tweet.includes(:user)
    @new = Tweet.includes(:user).last(4)
    @like = Like.new
  end

  def show
    @like = Like.new
  end

  def new
    @tweet = Tweet.new
    @images = @tweet.toukouimages.build
  end

 
  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      tag_list = tag_params[:tag_names].split(/[[:blank:]]+/).select(&:present?)
      if tag_list.length < 6
        @tweet.save_tags(tag_list)
      end
      redirect_to root_path, notice: 'Itemを投稿しました'
    else
      redirect_to new_tweet_path, notice: 'URL以外の全ての項目を入力してください'
    end

  end

  def edit
  end

  def update
    if @tweet.update(tweet_update_params)
      redirect_to root_path
    else
      redirect_to edit_tweet_path(@tweet)
    end
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to root_path, notice:'itemを削除しました'
  end

  

private
  def tweet_params
    params.require(:tweet).permit(:catchcopy, :text, :category_id, :url, :brand_id, toukouimages_attributes: [:image]).merge(user_id: current_user.id)
  end

  def tag_params
    params.require(:tweet).permit(:tag_names)
  end

  def tweet_update_params
    params.require(:tweet).permit(:catchcopy, :text, :category_id, :url, :brand_id, [toukouimages_attributes: [:image, :_destroy, :id]]).merge(user_id: current_user.id)
  end

  def set_item
    @tweet = Tweet.find(params[:id])
  end

  def set_brand
    @parents = Category.all
    @brand = Brand.all
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_brand, only: [:home, :show, :like]

  def home
    @user = User.find(params[:id])
    @quest = Quest.find_by(user_id: @user.id)
    @tweets = @user.tweets.last(4)
    @likes = Like.where(user_id: @user.id).last(4)
    @brands = Brand.find_by(user_id: @user.id)
  end


  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @tweets = @user.tweets
  end

  def like
    @user = User.find(params[:id])
    @likes = Like.where(user_id: @user.id)
  end
end

private

private
  def set_brand
    @parents = Category.all
    @brand = Brand.all
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/favorrite_helper.rb
module FavorriteHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Awaker
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/shared/_form2.html.haml
.item
  .item__title
    .item__title__title
      新規投稿
  .item__form
    .item__contents
      = form_with model: @tweet, local: true do |f|
        %h3
          アイテム画像を選択(5枚まで)
        .post__drop__box__container
          .prev-content
          .item__contents__photoflame__container
            %label{for: "item_images_attributes_0_image", class: "item__contents__photoflame__container__label-box hidden-field", id: "label-box--0"}
              %pre.item__contents__photoflame__container__label-box__text-visible クリックしてファイルをアップロード
          .hidden-content
            = f.fields_for :toukouimages do |i|
              %label{class: "hidden-field first"}
                クリックしてファイルをアップロード
                = i.file_field :image, class: "hidden-field"
              %input{class:"hidden-field", type: "file", name: "tweet[toukouimages_attributes][1][image]", id: "tweet_toukouimages_attributes_1_image" }
              %input{class:"hidden-field", type: "file", name: "tweet[toukouimages_attributes][2][image]", id: "tweet_toukouimages_attributes_2_image" }
              %input{class:"hidden-field", type: "file", name: "tweet[toukouimages_attributes][3][image]", id: "tweet_toukouimages_attributes_3_image" }
              %input{class:"hidden-field", type: "file", name: "tweet[toukouimages_attributes][4][image]", id: "tweet_toukouimages_attributes_4_image" }
        

        .item__date
        %h3
          キャッチコピー(タイトル)
        = f.text_field :catchcopy, placeholder: "例)この季節にぴったりのアイテム！" , rows: "10",class: 'item__date__comment__title'
        %h3
          アイテムのURL(販売ページなど)
        = f.text_field :url, placeholder: "商品ページのリンクなど" , rows: "10",class: 'item__date__comment__title'
        %h3
          紹介文
        = f.text_area :text, placeholder: "紹介文を入力" , rows: "10",class: 'item__date__comment__text'
        %h3
          カテゴリー
        .cp_ipselect.cp_sl01
          = f.collection_select :category_id, @parents, :id, :name, { prompt: "---" }
        %h3
          ブランド
        .cp_ipselect.cp_sl01
          = f.collection_select :brand_id, @brand, :id, :name, { prompt: "---" }
        %h3
          タグ(5個まで)
        = f.text_field :tag_names, placeholder: "例)おすすめ, 長袖, 限定モデル,",class: 'item__date__comment__title', id: 'tag'
        
        .item__date__bottan
          .item__date__bottan__shop
            = f.submit "投稿する", class: 'item__date__bottan__shop__send'
            
      

app/views/shared/_itemsview.html.haml
.iitem
  .test
    .iitem__title
      .iitem__title__name
        = link_to "/",class:"item__title__name" do
          %i.fas.fa-angle-double-left
      .iitem__title__nam
        = link_to home_user_path(id: @tweet.user.id),class:"item__title__na" do
          = @tweet.user.nickname
        さんの投稿♪
    .iitem-image
      .iitem__image
        %ul
          %li
            #mainImage
              = image_tag @tweet.toukouimages.first.image.url, class: "iitem__image__photo"
      .iitem__sub-image
        #imageList
          %ul
            - @tweet.toukouimages.each do |tweet|
              =image_tag tweet.image.url, class: "iitem__image__photo__list"
        - if user_signed_in? && current_user.id == @tweet.user_id
          = link_to edit_tweet_path(@tweet), class:"item__date__bottan__shop__send width20" do
            商品を編集
          = link_to tweet_path(@tweet), method: :delete, class: "item__date__bottan__shop__send width20" do
            %i.fa.fa-trash 
            削除する
    .iitem__date
      .iitem__date__catedategory
        = @tweet.catchcopy
        .iitem__date__catedategory__brand
          カテゴリー：
          = @tweet.category.name
        .iitem__date__catedategory__brand
          ブランド：
          = @tweet.brand.name
        - if @tweet.url.present?
          .iitem__date__catedategory__brand.flex
            商品ページ：
            .iitem__date__bottan__shop
              = link_to "#{@tweet.url}" do
                商品ページへ
        .tags
          - @tweet.tags.each do |tag|
            .iitem__date__catedategory__tag
              = tag.tag_name
          
      
      .iitem__date__bottan
        .iitem__date__bottan__good
          = link_to "https://twitter.com/share?ref_src=twsrc%5Etfw", "Tweet", data: {text: "【MITETE】このアイテムがおすすめ！是非、みてみて！", hashtags: "#MITETE", show_count:"false"}, class: "twitter-share-button" 
          %script{:async => "", :charset => "utf-8", :src => "https://platform.twitter.com/widgets.js"}
          - if current_user.already_liked?(@tweet)
            = button_to tweet_like_path(@tweet), method: :delete, class: "iitem__date__bottan__good__push" do
              登録済み
              %i.fas.fa-star
              = @tweet.likes.count
          - else
            = button_to tweet_likes_path(@tweet), class: "iitem__date__bottan__good__push" do
              お気に入り
              %i.far.fa-star
              = @tweet.likes.count
         
         
      .iitem__date__comment
        = @tweet.text

app/views/shared/_likelist.html.haml
.item
  - new.each do |like|
    - tweet = Tweet.find_by(id: like.tweet_id)
    .item__box
      = link_to "/tweets/#{tweet.id}", method: :get, class: "item__link" do
        = image_tag tweet.toukouimages.first.image.url, class: "item__box__view"
      .item__box__box
        - if user_signed_in? && current_user.id == tweet.user_id
          = link_to "/tweets/#{tweet.id}", method: :delete, class: "item__box__delete" do
            %i.fas.fa-window-close
      .item__name
        .side-bar__menue__device
          = link_to "/users/#{tweet.user.id}",class:"side-bar__menue__link" do
            = image_tag "first-icon.PNG" ,class: "side-bar__menue__device__icon space"
        .side-bar__menue__copy
          = tweet.catchcopy
        .side-bar__menue__star
          %i.fas.fa-star
          = tweet.likes.count
        

app/views/shared/_mypage_bar.html.haml
.side-bar
  .side-bar__user
    .side-bar__user__name
      = @nickname
      %br/
      マイページ
  .side-bar__menue
    = link_to "/",class:"side-bar__menue__link" do
      HOME
  .side-bar__menue
    = link_to "#",class:"side-bar__menue__link" do
      プロフィール
  .side-bar__menue
    = link_to "/users/#{current_user.id}",class:"side-bar__menue__link" do
      自分の投稿
  .side-bar__menue
    = link_to "/users/#{current_user.id}/like",class:"side-bar__menue__link" do
      いいね
  .side-bar__menue
    = link_to "#",class:"side-bar__menue__link" do
      設定
  .side-bar__menue
    = link_to destroy_user_session_path, method: :delete, class:"side-bar__menue__link" do
      ログアウト

app/views/shared/_new-list.html.haml
 
.item
  - new.each do |tweet|
    .item__box
      = link_to "/tweets/#{tweet.id}", method: :get, class: "item__link" do
        = image_tag tweet.toukouimages.first.image.url, class: "item__box__view"
      .item__box__box
        - if user_signed_in? && current_user.id == tweet.user_id
          = link_to "/tweets/#{tweet.id}", method: :delete, class: "item__box__delete" do
            %i.fas.fa-window-close
      .item__name
        .side-bar__menue__device
          = link_to "/users/#{tweet.user.id}",class:"side-bar__menue__link" do
            = image_tag "first-icon.PNG" ,class: "side-bar__menue__device__icon space"
        .side-bar__menue__copy
          = tweet.catchcopy
        .side-bar__menue__star
          %i.fas.fa-star
          = tweet.likes.count
        

app/views/shared/_side_bar.html.haml
.side-bar
  .side-bar__user
    = link_to "/",class:"side-bar__user__link" do
      = image_tag "111.png" ,class: "side-bar__user__icon"
    -# - if user_signed_in?
    -#   Welcome!
    -#   = current_user.nickname
    -# - else
    -#   MITETEへ
    -#   ようこそ！
      
    .search__box
      = form_with(url: tweets_searches_path, local: true, method: :get, class: "search__box__form") do |form|
        = form.text_field :keyword, placeholder: "投稿を検索する", class: "search__box__input"
        = button_tag type: 'submit', class: "search__box__btn" do
          %i.fas.fa-search

  .side-bar__decolate
    .side-bar__menue
      - if user_signed_in?
        %ul.mycate
          %li.side-bar__menue__device.pulldown
            %i.fas.fa-list
            = link_to "カテゴリ","#",class:"side-bar__menue__link"
            %ul.top__menue
              - @parents.each do |category|
                %li.top__menue__item
                  = form_with(url: tweets_searches_path, local: true, method: :get, class: "top__menue__item__form") do |form|
                    = form.text_field :keyword, value: "#{category.name}", class: "top__menue__item__form__text"
                    = form.submit "#{category.name}", class: "top__menue__item__form__btn"
          %li.side-bar__menue__device.pulldown
            %i.fas.fa-list
            = link_to "ブランド","#",class:"side-bar__menue__link"
            %ul.top__menue
              - @brand.each do |category|
                %li.top__menue__item
                  = form_with(url: tweets_searches_path, local: true, method: :get, class: "top__menue__item__form") do |form|
                    = form.text_field :keyword, value: "#{category.name}", class: "top__menue__item__form__text"
                    = form.submit "#{category.name}", class: "top__menue__item__form__btn"
          %li.side-bar__menue__device.pulldown
            = link_to commercial_tweets_path,class:"side-bar__menue__link " do
              [MITETE]って何?
          - unless current_user.admin?
            %li.side-bar__menue__device.pulldown
              = link_to home_user_path(id: current_user.id),class:"side-bar__menue__link" do
                = image_tag "first-icon.PNG" ,class: "side-bar__menue__device__icon icon-height"
                = current_user.nickname
              %ul.top__menue
                %li.top__menue__item__form__btn
                  = link_to home_user_path(id: current_user.id),class:"btn" do
                    プロフィール
                %li.top__menue__item__form__btn
                  = link_to new_tweet_path,class:"btn" do
                    投稿する
                %li.top__menue__item__form__btn
                  = link_to "/users/#{current_user.id}",class:"btn" do
                    自分の投稿
                %li.top__menue__item__form__btn
                  = link_to "/users/#{current_user.id}/like",class:"btn" do
                    いいねした投稿
                %li.top__menue__item__form__btn
                  = link_to destroy_user_session_path, method: :delete, class:"btn" do
                    ログアウト
          -else
            %li.side-bar__menue__device.pulldown
              = link_to "/users/",class:"side-bar__menue__link" do
                = image_tag "first-icon.PNG" ,class: "side-bar__menue__device__icon icon-height"
                = current_user.nickname
              %ul.top__menue
                %li.top__menue__item__form__btn
                  = link_to "#",class:"btn" do
                    プロフィール
                %li.top__menue__item__form__btn
                  = link_to admin_users_path,class:"btn" do
                    管理画面
                %li.top__menue__item__form__btn
                  = link_to destroy_user_session_path, method: :delete, class:"btn" do
                    ログアウト
      - else
        .side-bar__menue__device
        = link_to new_user_session_path,class:"side-bar__menue__link" do
          サインイン
        .side-bar__menue__device
        = link_to new_user_registration_path,class:"side-bar__menue__link" do
          新規登録
    

    