config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  root to: 'tweets#index'
  namespace :tweets do
    resources :searches, only: :index
  end
  resources :searches, only: :index
  resources :users do
    member do
      get 'like'
      get 'home'
    end
  end

  resources :quests, only: [:new, :create, :show, :destroy] do
    resources :brands
  end
  namespace :admin do
    resources :users
  end
  resources :tweets do
    collection do
      get 'commercial'
    end
    resources :likes, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user

  def index
    @users = User.all.order("created_at DESC")
    @quest = Quest.all
    @brand = Brand.all
  end

  private
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_brand, only: [:home, :show, :like]

  def home
    @user = User.find(params[:id])
    @quest = Quest.find_by(user_id: @user.id)
    @tweets = @user.tweets.last(4)
    @likes = Like.where(user_id: @user.id).last(4)
    @brands = Brand.find_by(user_id: @user.id)
  end


  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @tweets = @user.tweets
  end

  def like
    @user = User.find(params[:id])
    @likes = Like.where(user_id: @user.id)
  end
end

private

private
  def set_brand
    @parents = Category.all
    @brand = Brand.all
  end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.haml
.side-bar
  .side-bar__user
    = link_to "/",class:"side-bar__user__link" do
      = image_tag "111.png" ,class: "side-bar__user__icon"
      
    .search__box
      管理者専用ページ

  .side-bar__decolate
    .side-bar__menue
      %ul.mycate
        %li.side-bar__menue__device.pulldown
          = link_to "#",class:"side-bar__menue__link " do
            [MITETE]って何?       
        %li.side-bar__menue__device.pulldown
          = link_to "/users/",class:"side-bar__menue__link" do
            = image_tag "first-icon.PNG" ,class: "side-bar__menue__device__icon icon-height"
            = current_user.nickname
          %ul.top__menue
            %li.top__menue__item__form__btn
              = link_to "#",class:"btn" do
                プロフィール
            %li.top__menue__item__form__btn
              = link_to admin_users_path,class:"btn" do
                管理画面
            %li.top__menue__item__form__btn
              = link_to destroy_user_session_path, method: :delete, class:"btn" do
                ログアウト

.iitem
  .fontsize_midium.margintop_big
    ブランド申請一覧
  .test.admin
    - if @quest.present?
      - @quest.each do |quest|
        .admin__box
          user_id:
          = quest.user_id
          ブランド名:
          = quest.brandname
          = link_to quest_path(quest.id),class:"iitem__date__bottan__shop" do
            確認する
    - else
      .admin__box
        現在、申請はありません
  .fontsize_midium.margintop_big
    ブランド一覧
  .test.admin
    - @brand.each do |quest|
      .admin__box
        ID:
        = quest.id
        user_id:
        = quest.user_id
        ブランド名:
        = quest.name

  .fontsize_midium.margintop_big
    管理画面：ユーザー一覧
  .test.admin
    - @users.each do |user|
      .admin__box
        ID:
        = user.id
        ユーザー名:
        = user.nickname
        |
        = user.created_at